name: Docker Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ github.ref_name == 'main' && 'ghcr.io/aryezz/map-art-helper-bot:latest' || format('ghcr.io/aryezz/map-art-helper-bot:{0},ghcr.io/aryezz/map-art-helper-bot:dev', github.ref_name) }}
          cache-from: type=registry,ref=ghcr.io/aryezz/map-art-helper-bot:latest
          cache-to: type=inline
